### ISSUE TITLE
On running "docker run --privileged -P fish/prometheus-demo " i got output as below and exposed services are not accessible. 

### ISSUE THREAD

**Issue by kuldeepdarmwal** [discordianfish/prometheus-demo#2]
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
time="2015-10-27T10:23:06.403434283Z" level=error msg="[graphdriver] prior storage driver \"btrfs\" failed: prerequisites for driver not satisfied (wrong filesystem?)"
time="2015-10-27T10:23:06.403889466Z" level=fatal msg="Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)"
Timed out trying to connect to internal docker host.
stdin: is not a tty

**Comment by discordianfish** [comment]
Can you start other docker containers? Looks like a Docker issue, not a issue with this repo.

**Comment by kuldeepdarmwal** [comment]
@discordianfish thnx for suggestion... :+1:
